-- create user database
CREATE TABLE `retailer`.`login` (`id` INT NOT NULL AUTO_INCREMENT , `user_name` VARCHAR(255) NULL DEFAULT NULL , `password` VARCHAR(255) NULL DEFAULT NULL ,`order_form` VARCHAR(255) NULL DEFAULT NULL, `view_order` VARCHAR(255) NULL DEFAULT NULL , `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;


-- response table 
CREATE TABLE `retailer`.`response` (`id` INT NOT NULL AUTO_INCREMENT , `user_name` VARCHAR(255) NULL DEFAULT NULL , `width` VARCHAR(255) NULL DEFAULT NULL , `color` VARCHAR(255) NULL DEFAULT NULL , `design_name` VARCHAR(255) NULL DEFAULT NULL , `quantity` INT(255) NULL DEFAULT NULL , `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

